# Generated by Django 5.2.13 on 2026-04-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50, unique=True)),
                ('oquv_yili', models.CharField(max_length=9)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'db_table': 'guruhlar',
            },
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tartib', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'db_table': 'kurslar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='OtaOnaTalaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qarindoshlik', models.CharField(choices=[('OTA', 'Ota'), ('ONA', 'Ona'), ('VASIY', 'Vasiy')], max_length=20)),
                ('asosiy', models.BooleanField(default=True)),
                ('xabar_olish_mumkin', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ota-ona-Talaba',
                'verbose_name_plural': 'Ota-ona-Talabalar',
                'db_table': 'ota_ona_talabalar',
            },
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('talaba_id', models.CharField(max_length=20, unique=True)),
                ('telefon', models.CharField(max_length=13)),
                ('ota_ona_telefon', models.CharField(max_length=13)),
                ('manzil', models.TextField(blank=True)),
                ('qabul_sana', models.DateField(auto_now_add=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
                'db_table': 'talabalar',
                'ordering': ['familiya', 'ism'],
            },
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('kodi', models.CharField(max_length=20, unique=True)),
                ('tavsif', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'db_table': 'yonalishlar',
            },
        ),
    ]
