# Generated by Django 5.2.13 on 2026-04-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guruh',
            name='rahbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rahbarlik_guruhlari', to='users.oqituvchi'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guruhlar', to='students.kurs'),
        ),
        migrations.AddField(
            model_name='otaonatalaba',
            name='ota_ona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolalar', to='users.otaona'),
        ),
        migrations.AddField(
            model_name='talaba',
            name='guruh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talabalar', to='students.guruh'),
        ),
        migrations.AddField(
            model_name='otaonatalaba',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_onalar', to='students.talaba'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guruhlar', to='students.yonalish'),
        ),
        migrations.AlterUniqueTogether(
            name='otaonatalaba',
            unique_together={('ota_ona', 'talaba')},
        ),
        migrations.AlterUniqueTogether(
            name='guruh',
            unique_together={('nomi', 'oquv_yili')},
        ),
    ]
