# Generated by Django 5.2.13 on 2026-04-09 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        ('users', '0002_remove_foydalanuvchi_foydalanuvc_usernam_348d19_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guruh',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kurs',
            options={'ordering': ['tartib']},
        ),
        migrations.AlterModelOptions(
            name='otaonatalaba',
            options={},
        ),
        migrations.AlterModelOptions(
            name='talaba',
            options={},
        ),
        migrations.AlterModelOptions(
            name='yonalish',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='guruh',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='otaonatalaba',
            name='asosiy',
        ),
        migrations.RemoveField(
            model_name='otaonatalaba',
            name='xabar_olish_mumkin',
        ),
        migrations.RemoveField(
            model_name='talaba',
            name='qabul_sana',
        ),
        migrations.RemoveField(
            model_name='talaba',
            name='yangilangan_vaqt',
        ),
        migrations.RemoveField(
            model_name='yonalish',
            name='tavsif',
        ),
        migrations.AlterField(
            model_name='guruh',
            name='rahbar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.oqituvchi'),
        ),
        migrations.AlterField(
            model_name='otaonatalaba',
            name='ota_ona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.otaona'),
        ),
        migrations.AlterField(
            model_name='otaonatalaba',
            name='qarindoshlik',
            field=models.CharField(choices=[('OTA', 'Ota'), ('ONA', 'Ona'), ('VASIY', 'Vasiy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='otaonatalaba',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.talaba'),
        ),
        migrations.RemoveField(
            model_name='guruh',
            name='yaratilgan_vaqt',
        ),
    ]
