# Generated by Django 5.2.13 on 2026-04-09 10:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('roli', models.CharField(choices=[('ADMIN', 'Administrator'), ('OQITUVCHI', "O'qituvchi"), ('OTA_ONA', 'Ota-ona')], default='OQITUVCHI', max_length=10)),
                ('telefon', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998\\d{9}$')])),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tasdiqlangan', models.BooleanField(default=False)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Oqituvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xodim_id', models.CharField(max_length=20, unique=True)),
                ('mutaxassislik', models.CharField(max_length=200)),
                ('ishga_olingan_sana', models.DateField(auto_now_add=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('foydalanuvchi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oqituvchi_profili', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oqituvchilar',
            },
        ),
        migrations.CreateModel(
            name='OtaOna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasbi', models.CharField(blank=True, max_length=200)),
                ('manzil', models.TextField(blank=True)),
                ('xabar_ushlubi', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('SMS', 'SMS'), ('HAMMA', 'Hammasi')], default='TELEGRAM', max_length=20)),
                ('foydalanuvchi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ota_ona_profili', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ota_onalar',
            },
        ),
        migrations.AddIndex(
            model_name='foydalanuvchi',
            index=models.Index(fields=['username'], name='foydalanuvc_usernam_348d19_idx'),
        ),
        migrations.AddIndex(
            model_name='foydalanuvchi',
            index=models.Index(fields=['telefon'], name='foydalanuvc_telefon_ed502d_idx'),
        ),
        migrations.AddIndex(
            model_name='foydalanuvchi',
            index=models.Index(fields=['roli'], name='foydalanuvc_roli_502bb7_idx'),
        ),
    ]
