# Generated by Django 5.2.13 on 2026-04-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='foydalanuvchi',
            name='foydalanuvc_usernam_348d19_idx',
        ),
        migrations.RemoveIndex(
            model_name='foydalanuvchi',
            name='foydalanuvc_telefon_ed502d_idx',
        ),
        migrations.RemoveIndex(
            model_name='foydalanuvchi',
            name='foydalanuvc_roli_502bb7_idx',
        ),
        migrations.RemoveField(
            model_name='oqituvchi',
            name='aktiv',
        ),
        migrations.RemoveField(
            model_name='oqituvchi',
            name='ishga_olingan_sana',
        ),
        migrations.RemoveField(
            model_name='otaona',
            name='kasbi',
        ),
        migrations.RemoveField(
            model_name='otaona',
            name='xabar_ushlubi',
        ),
        migrations.AddField(
            model_name='otaona',
            name='telegram_xabar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='telefon',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
