# Generated by Django 5.2.13 on 2026-04-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('holat', models.CharField(choices=[('KELDI', '✅ Qatnashdi'), ('KELMADI', '❌ Qatnashmadi')], default='KELDI', max_length=10)),
                ('sabab', models.CharField(choices=[('SABABSIZ', 'Sababsiz'), ('KASAL', 'Kasal'), ('RUXSAT', 'Ruxsat bilan'), ('KECHIKDI', 'Kechikish')], default='SABABSIZ', max_length=20)),
                ('izoh', models.TextField(blank=True)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'db_table': 'davomatlar',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('kodi', models.CharField(max_length=20, unique=True)),
                ('qisqa_nomi', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'db_table': 'fanlar',
            },
        ),
        migrations.CreateModel(
            name='Jadval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hafta_kuni', models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba')])),
                ('boshlanish_vaqti', models.TimeField()),
                ('tugash_vaqti', models.TimeField()),
                ('xona', models.CharField(max_length=50)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Jadval',
                'verbose_name_plural': 'Jadvallar',
                'db_table': 'jadval',
            },
        ),
    ]
