# Generated by Django 5.2.13 on 2026-04-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='davomat',
            name='kiritgan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.oqituvchi'),
        ),
        migrations.AddField(
            model_name='davomat',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomatlar', to='students.talaba'),
        ),
        migrations.AddField(
            model_name='davomat',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.fan'),
        ),
        migrations.AddField(
            model_name='jadval',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadval', to='attendance.fan'),
        ),
        migrations.AddField(
            model_name='jadval',
            name='guruh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadval', to='students.guruh'),
        ),
        migrations.AddField(
            model_name='jadval',
            name='oqituvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadval', to='users.oqituvchi'),
        ),
        migrations.AddField(
            model_name='davomat',
            name='jadval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.jadval'),
        ),
        migrations.AlterUniqueTogether(
            name='jadval',
            unique_together={('guruh', 'fan', 'hafta_kuni', 'boshlanish_vaqti')},
        ),
        migrations.AlterUniqueTogether(
            name='davomat',
            unique_together={('talaba', 'fan', 'sana')},
        ),
    ]
