# Generated by Django 5.2.13 on 2026-04-09 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('users', '0002_remove_foydalanuvchi_foydalanuvc_usernam_348d19_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='davomat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jadval',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='jadval',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='davomat',
            name='jadval',
        ),
        migrations.RemoveField(
            model_name='davomat',
            name='yangilangan_vaqt',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='qisqa_nomi',
        ),
        migrations.AlterField(
            model_name='davomat',
            name='holat',
            field=models.CharField(choices=[('KELDI', 'Qatnashdi'), ('KELMADI', 'Qatnashmadi')], default='KELDI', max_length=10),
        ),
        migrations.AlterField(
            model_name='davomat',
            name='sabab',
            field=models.CharField(choices=[('SABABSIZ', 'Sababsiz'), ('KASAL', 'Kasal'), ('RUXSAT', 'Ruxsat bilan')], default='SABABSIZ', max_length=10),
        ),
        migrations.AlterField(
            model_name='jadval',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.fan'),
        ),
        migrations.AlterField(
            model_name='jadval',
            name='oqituvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.oqituvchi'),
        ),
        migrations.RemoveField(
            model_name='jadval',
            name='aktiv',
        ),
    ]
