# Generated by Django 5.2.13 on 2026-04-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xabarnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('WARNING', '⚠️ Ogohlantirish'), ('ALERT', '🔴 Xabar'), ('REPORT', '📊 Hisobot')], max_length=20)),
                ('sarlavha', models.CharField(max_length=200)),
                ('matn', models.TextField()),
                ('nb_soni', models.IntegerField(default=0)),
                ('ketma_ket_nb', models.IntegerField(default=0)),
                ('yuborildi', models.BooleanField(default=False)),
                ('yuborilgan_vaqt', models.DateTimeField(blank=True, null=True)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xabarnoma',
                'verbose_name_plural': 'Xabarnomalar',
                'db_table': 'xabarnomalar',
                'ordering': ['-yaratilgan_vaqt'],
            },
        ),
        migrations.CreateModel(
            name='XabarnomaSozlamalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_xabar', models.BooleanField(default=True)),
                ('sms_xabar', models.BooleanField(default=False)),
                ('nb_chegarasi', models.IntegerField(default=3)),
                ('kunlik_hisobot', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Xabarnoma sozlamasi',
                'verbose_name_plural': 'Xabarnoma sozlamalari',
                'db_table': 'xabarnoma_sozlamalari',
            },
        ),
    ]
