# Generated by Django 5.2.13 on 2026-04-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('students', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xabarnoma',
            name='ota_ona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xabarnomalar', to='users.otaona'),
        ),
        migrations.AddField(
            model_name='xabarnoma',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xabarnomalar', to='students.talaba'),
        ),
        migrations.AddField(
            model_name='xabarnomasozlamalari',
            name='ota_ona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xabarnoma_sozlamalari', to='users.otaona'),
        ),
    ]
