# Generated by Django 5.2.13 on 2026-04-09 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('users', '0002_remove_foydalanuvchi_foydalanuvc_usernam_348d19_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xabarnoma',
            options={},
        ),
        migrations.RemoveField(
            model_name='xabarnoma',
            name='ketma_ket_nb',
        ),
        migrations.RemoveField(
            model_name='xabarnoma',
            name='nb_soni',
        ),
        migrations.RemoveField(
            model_name='xabarnoma',
            name='yuborilgan_vaqt',
        ),
        migrations.AlterField(
            model_name='xabarnoma',
            name='ota_ona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.otaona'),
        ),
        migrations.AlterField(
            model_name='xabarnoma',
            name='tur',
            field=models.CharField(choices=[('WARNING', 'Ogohlantirish'), ('ALERT', 'Xabar'), ('REPORT', 'Hisobot')], max_length=10),
        ),
        migrations.DeleteModel(
            name='XabarnomaSozlamalari',
        ),
    ]
