# Generated by Django 5.2.13 on 2026-04-09 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_xabarnoma_options_and_more'),
        ('users', '0002_remove_foydalanuvchi_foydalanuvc_usernam_348d19_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xabarnoma',
            options={'ordering': ['-yaratilgan_vaqt']},
        ),
        migrations.AddField(
            model_name='xabarnoma',
            name='yuborilgan_vaqt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xabarnoma',
            name='ota_ona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xabarnomalar', to='users.otaona'),
        ),
        migrations.AlterField(
            model_name='xabarnoma',
            name='tur',
            field=models.CharField(choices=[('WARNING', 'Ogohlantirish'), ('ALERT', 'Xabar'), ('REPORT', 'Hisobot')], default='ALERT', max_length=10),
        ),
        migrations.CreateModel(
            name='XabarnomaSozlamalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_xabar', models.BooleanField(default=True)),
                ('nb_chegarasi', models.IntegerField(default=5)),
                ('ota_ona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xabarnoma_sozlamalari', to='users.otaona')),
            ],
            options={
                'db_table': 'xabarnoma_sozlamalari',
            },
        ),
    ]
